# Generated by Django 4.2 on 2023-04-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.TextField(default=123456789, verbose_name='Phone number'),
            preserve_default=False,
        ),
    ]
