# Generated by Django 4.2 on 2023-04-20 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_user_is_employee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appointment',
        ),
    ]
