# Generated by Django 4.2 on 2023-04-20 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='start_date',
        ),
        migrations.AddField(
            model_name='appointment',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 20, 20, 38, 32, 447342), verbose_name='Appointment end time'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 20, 20, 38, 32, 447342), verbose_name='Appointment start time'),
        ),
    ]
