# Generated by Django 4.2 on 2023-04-20 16:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_remove_appointment_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 20, 16, 40, 17, 631512, tzinfo=datetime.timezone.utc), verbose_name='Appointment end time'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 20, 16, 40, 17, 631512, tzinfo=datetime.timezone.utc), verbose_name='Appointment start time'),
        ),
    ]
