# Generated by Django 4.2 on 2023-04-20 16:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_alter_appointment_end_alter_appointment_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end',
            field=models.TimeField(default=datetime.datetime(2023, 4, 20, 16, 51, 12, 775745, tzinfo=datetime.timezone.utc), verbose_name='Appointment end time'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start',
            field=models.TimeField(default=datetime.datetime(2023, 4, 20, 16, 51, 12, 775745, tzinfo=datetime.timezone.utc), verbose_name='Appointment start time'),
        ),
    ]
