# Generated by Django 4.2 on 2023-04-20 16:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0007_appointment_date_alter_appointment_end_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 20, 16, 58, 28, 454862, tzinfo=datetime.timezone.utc), verbose_name='Appointment end time'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2023, 4, 20, 16, 58, 28, 454862, tzinfo=datetime.timezone.utc), verbose_name='Appointment start time'),
        ),
    ]
