# Generated by Django 4.2 on 2023-05-06 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0012_alter_appointment_employee_id_alter_appointment_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 6, 17, 54, 22, 718212), verbose_name='Appointment end time'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 6, 17, 54, 22, 718212), verbose_name='Appointment start time'),
        ),
    ]
