# Generated by Django 4.2 on 2023-05-07 11:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0014_alter_appointment_end_alter_appointment_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='end',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 7, 15, 3, 48, 583739), verbose_name='Appointment end time'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='start',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 7, 15, 3, 48, 583739), verbose_name='Appointment start time'),
        ),
    ]
